#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Install Nginx if not already installed
apt-get update -y
apt-get install -y nginx

# Create a basic HTML page with the required content
echo "Holberton School for the win!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure the redirection
redirect_config="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
# Configure custom 404 page
error_config="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"

# Update the default site configuration
sed -i "/server_name _;/a $redirect_config" /etc/nginx/sites-available/default
sed -i "/server_name _;/a $error_config" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
