#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Install Nginx if not already installed
apt-get update -y
apt-get install -y nginx

# Create a basic HTML page
echo "Holberton School for the win!" | tee /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Update Nginx configuration
sed -i "/server_name _;/a \\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

